### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by flawsom** [Zeddxx/ani-fire#31]
Application error: a client-side exception has occurred (see the browser console for more information).
![Screenshot (13)](https://github.com/Zeddxx/ani-fire/assets/64182228/9a834f9c-06bd-4328-9b17-e5789ecd96bf)
![Screenshot (14)](https://github.com/Zeddxx/ani-fire/assets/64182228/075ee272-9a41-4351-a47b-c7e1da85c60b)

why is this happening ( i tried it on multiple platforms/Devices )

**Comment by Zeddxx** [comment]
This is due to scrapping I guess, I am not getting the required data from the api,
Getting data as undefined.

**Comment by Zeddxx** [comment]
Currently api error: 
<img width="1024" alt="image" src="https://github.com/Zeddxx/ani-fire/assets/119150520/34817683-0f65-4344-93f8-715fe000e782">

**Comment by Zeddxx** [comment]
Current api streaming error: 
<img width="1024" alt="image" src="https://github.com/Zeddxx/ani-fire/assets/119150520/9bcc4407-fa86-40ab-a36f-495442e2be24">

**Comment by flawsom** [comment]
Oh i see, so ig it will be like that for a while ( did u checked if the vercel instance for api isn,t rate limited ? )

**Comment by Zeddxx** [comment]
Nah nah this issue is from the scrapper as the key have some kind of issue,
As the route /home /:page are still working,
