### ISSUE TITLE
Switching between sub and dub doesn't wok

### ISSUE THREAD

**Issue by sbwgg** [Zeddxx/ani-fire#35]
**Describe the bug**
Switching between sub and dub doesn't work and you can't play episode.

**To Reproduce**
1. Go to ''anine'
2. Click on 'providers'

**Expected behavior**
Should play episode in dub ir sub.

**Comment by Zeddxx** [comment]
@sbwgg i haven’t yet implemented this functionality in upcoming days I will do that, currently busy with some stuff.

**Comment by Zeddxx** [comment]
@sbwgg added switch between sub and dub but i am not sure for how much anime will it work but for now i did it work somehow 🎉
