### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by GodxD69** [Zeddxx/ani-fire#38]
I hosted this site on vercel 
Filled api and everything
Everything working but when I play the video /episode, it only loads.

I might have done something wrong or it is a bug. Can someone help me out ?

**Comment by Zeddxx** [comment]
I guess you used the new api for this..(will update this project like new api one by eod)

**Comment by Zeddxx** [comment]
@GodxD69 fixed this!

**Comment by FujiwaraChoki** [comment]
Thank you @Zeddxx
