### ISSUE TITLE
trying to run it locally

### ISSUE THREAD

**Issue by ShawnIsADev** [Zeddxx/ani-fire#40]
**Describe the bug**
cant run it locally

![image](https://github.com/user-attachments/assets/d7614b94-dca0-43da-b346-f3e7d3558302)
all i've done so far after cloning is add the .env to the root and enter the .env details. 
![image](https://github.com/user-attachments/assets/28b5b191-9d6a-4d82-b142-9c00c3023229)
also for the UPLOADTHING ID is that the project name? sorry im dumb lol

@Zeddxx

**Comment by Zeddxx** [comment]
The routes for the apis have been changed.

**Comment by ShawnIsADev** [comment]
ohhh. do you know where i can get the new routes? sorry if im being a pain

**Comment by ShawnIsADev** [comment]
nvm just saw in the other issue comment you'll have a fix for it eventually my bad
