### ISSUE TITLE
Homepage is empty 

### ISSUE THREAD

**Issue by PacaHat** [Zeddxx/ani-fire#47]
I have created the .env file and filled up that but still there is nothing in the homepage 

And I think you need to improve the file structure it's so messed up 

![Screenshot_2024-11-21-15-46-33-18](https://github.com/user-attachments/assets/5fc1d0d7-656f-4221-b080-954f8df24d0a)

**Comment by Zeddxx** [comment]
Working on improving the file structure… as for the issue i have already gave a fix to these: [issue](https://github.com/Zeddxx/ani-fire/issues/39)
